# Netlify build & redirects configuration.
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "https://www.annakreslavskaya.com/*"
  to   = "https://annakreslavskaya.com/:splat"
  status = 301
  force  = true
